### ISSUE TITLE
Parser fails when encountering type annotation

### ISSUE THREAD

**Issue by gunnarmorling** [Netflix/rewrite#15]
I've a specific usage of Java 8 type annotations (JSR 308) which makes the parser fail. To reproduce, parse these classes:

```java
package com;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE_USE)
public @interface SomeAnno {
}
```

```java
package com;

public interface SomeInterface<T> {
	void foo();
}
```

```java
package com;

class SomeImpl implements SomeInterface<Object @SomeAnno[]> {

	@Override
	public void foo() {
	}
}
```

That's the stacktrace I'm getting:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -29
	at java.lang.String.substring(String.java:1967)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.visitAnnotation(OracleJdkParserVisitor.kt:78)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.visitAnnotation(OracleJdkParserVisitor.kt:40)
	at com.netflix.devinsight.shaded.com.sun.tools.javac.tree.JCTree$JCAnnotation.accept(JCTree.java:2327)
	at com.netflix.devinsight.shaded.com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.convert(OracleJdkParserVisitor.kt:1026)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.convertAll(OracleJdkParserVisitor.kt:1058)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.visitMethod(OracleJdkParserVisitor.kt:617)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.visitMethod(OracleJdkParserVisitor.kt:40)
	at com.netflix.devinsight.shaded.com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
	at com.netflix.devinsight.shaded.com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.convert(OracleJdkParserVisitor.kt:1026)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.convertPossibleMultiVariable(OracleJdkParserVisitor.kt:1082)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.visitClass(OracleJdkParserVisitor.kt:279)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.visitClass(OracleJdkParserVisitor.kt:40)
	at com.netflix.devinsight.shaded.com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
	at com.netflix.devinsight.shaded.com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.convert(OracleJdkParserVisitor.kt:1026)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.convertAll(OracleJdkParserVisitor.kt:1058)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.visitCompilationUnit(OracleJdkParserVisitor.kt:311)
	at com.netflix.rewrite.parse.OracleJdkParserVisitor.visitCompilationUnit(OracleJdkParserVisitor.kt:40)
	at com.netflix.devinsight.shaded.com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:550)
	at com.netflix.devinsight.shaded.com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
	at com.netflix.rewrite.parse.OracleJdkParser.parse(OracleJdkParser.kt:112)
	at com.netflix.rewrite.parse.AbstractParser.parse(Parser.kt:69)
```

Interestingly, it doesn't happen if I change the type of the annotated element from `Object` (or any other reference type) to a primitive type such as `int`.

**Comment by jkschneider** [comment]
I'm not even sure how to read that! What does that do?

**Comment by gunnarmorling** [comment]
It applies that annotation to the component type of the given array type. What that means semantically, is up to the application using it of course.

A real-world example is Bean Validation 2.0, where [we're using it](http://beanvalidation.org/2.0/spec/#valueextractordefinition-examples) to mark the value type emitted by a given value extractor.
